# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=net.modfest
user=ModFest
slug=fireblanket
modId=fireblanket
modName=Fireblanket
modDescription=Performance, bugfixes, and utilities for ModFest events.
authors=jaskarth, unascribed
contributors=Patbox, IThundxr
license=AGPL-3.0-or-later
# Mod Version
baseVersion=0.10.0
# Branch Metadata
branch=fabric-26.3
tagBranch=fabric-26.3
compatibleVersions=26.3
compatibleLoaders=fabric, quilt, neoforge
