name: Build

on: [ push, pull_request ]

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup jdk
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
          # Opt-out of proprietary cache mechanism.
          cache-provider: basic

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            build/libs
            build/reports
            created_attestation_paths.txt
